name: binance_spot_plus
description: Unofficial Dart wrapper for Binance SPOT API (REST endpoints + Websockets).
version: 0.0.3
homepage: https://github.com/lostoy0/binance_spot
repository: https://github.com/lostoy0/binance_spot

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  convert: ^3.0.1
  crypto: ^3.0.1
  either_dart: ^1.0.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0